# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XBox_GUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(636, 420)
        self.centralWidget = QtGui.QWidget(mainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.modus_wahl = QtGui.QTabWidget(self.centralWidget)
        self.modus_wahl.setGeometry(QtCore.QRect(320, 10, 301, 351))
        self.modus_wahl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.modus_wahl.setObjectName(_fromUtf8("modus_wahl"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.drop_befehle_senden = QtGui.QPushButton(self.tab)
        self.drop_befehle_senden.setEnabled(False)
        self.drop_befehle_senden.setGeometry(QtCore.QRect(120, 180, 75, 23))
        self.drop_befehle_senden.setObjectName(_fromUtf8("drop_befehle_senden"))
        self.manuelle_befehle_senden = QtGui.QPushButton(self.tab)
        self.manuelle_befehle_senden.setEnabled(False)
        self.manuelle_befehle_senden.setGeometry(QtCore.QRect(120, 240, 75, 23))
        self.manuelle_befehle_senden.setObjectName(_fromUtf8("manuelle_befehle_senden"))
        self.Zustandsangabe_1 = QtGui.QTextBrowser(self.tab)
        self.Zustandsangabe_1.setGeometry(QtCore.QRect(10, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Zustandsangabe_1.setFont(font)
        self.Zustandsangabe_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Zustandsangabe_1.setObjectName(_fromUtf8("Zustandsangabe_1"))
        self.drop_befehle = QtGui.QComboBox(self.tab)
        self.drop_befehle.setEnabled(True)
        self.drop_befehle.setGeometry(QtCore.QRect(10, 150, 181, 22))
        self.drop_befehle.setObjectName(_fromUtf8("drop_befehle"))
        self.manuelle_befehle = QtGui.QLineEdit(self.tab)
        self.manuelle_befehle.setEnabled(False)
        self.manuelle_befehle.setGeometry(QtCore.QRect(0, 210, 191, 20))
        self.manuelle_befehle.setObjectName(_fromUtf8("manuelle_befehle"))
        self.modus_1_start = QtGui.QPushButton(self.tab)
        self.modus_1_start.setGeometry(QtCore.QRect(20, 50, 75, 23))
        self.modus_1_start.setObjectName(_fromUtf8("modus_1_start"))
        self.modus_1_stop = QtGui.QPushButton(self.tab)
        self.modus_1_stop.setEnabled(False)
        self.modus_1_stop.setGeometry(QtCore.QRect(110, 50, 75, 23))
        self.modus_1_stop.setCheckable(False)
        self.modus_1_stop.setObjectName(_fromUtf8("modus_1_stop"))
        self.empfange_button = QtGui.QPushButton(self.tab)
        self.empfange_button.setGeometry(QtCore.QRect(10, 100, 181, 41))
        self.empfange_button.setObjectName(_fromUtf8("empfange_button"))
        self.modus_wahl.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.programm_senden_1 = QtGui.QPushButton(self.tab_3)
        self.programm_senden_1.setEnabled(False)
        self.programm_senden_1.setGeometry(QtCore.QRect(20, 80, 161, 51))
        self.programm_senden_1.setObjectName(_fromUtf8("programm_senden_1"))
        self.programm_senden_2 = QtGui.QPushButton(self.tab_3)
        self.programm_senden_2.setEnabled(False)
        self.programm_senden_2.setGeometry(QtCore.QRect(20, 140, 161, 51))
        self.programm_senden_2.setObjectName(_fromUtf8("programm_senden_2"))
        self.Zustandsangabe_2 = QtGui.QTextBrowser(self.tab_3)
        self.Zustandsangabe_2.setEnabled(True)
        self.Zustandsangabe_2.setGeometry(QtCore.QRect(10, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Zustandsangabe_2.setFont(font)
        self.Zustandsangabe_2.setObjectName(_fromUtf8("Zustandsangabe_2"))
        self.modus_2_start = QtGui.QPushButton(self.tab_3)
        self.modus_2_start.setGeometry(QtCore.QRect(20, 50, 75, 23))
        self.modus_2_start.setObjectName(_fromUtf8("modus_2_start"))
        self.modus_2_stop = QtGui.QPushButton(self.tab_3)
        self.modus_2_stop.setEnabled(False)
        self.modus_2_stop.setGeometry(QtCore.QRect(110, 50, 75, 23))
        self.modus_2_stop.setCheckable(False)
        self.modus_2_stop.setObjectName(_fromUtf8("modus_2_stop"))
        self.modus_wahl.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.modus_3_senden = QtGui.QPushButton(self.tab_2)
        self.modus_3_senden.setEnabled(False)
        self.modus_3_senden.setGeometry(QtCore.QRect(20, 132, 161, 41))
        self.modus_3_senden.setObjectName(_fromUtf8("modus_3_senden"))
        self.Zustandsangabe_3 = QtGui.QTextBrowser(self.tab_2)
        self.Zustandsangabe_3.setEnabled(True)
        self.Zustandsangabe_3.setGeometry(QtCore.QRect(10, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Zustandsangabe_3.setFont(font)
        self.Zustandsangabe_3.setObjectName(_fromUtf8("Zustandsangabe_3"))
        self.modus_3_start = QtGui.QPushButton(self.tab_2)
        self.modus_3_start.setGeometry(QtCore.QRect(20, 50, 75, 23))
        self.modus_3_start.setObjectName(_fromUtf8("modus_3_start"))
        self.modus_3_stop = QtGui.QPushButton(self.tab_2)
        self.modus_3_stop.setEnabled(False)
        self.modus_3_stop.setGeometry(QtCore.QRect(110, 50, 75, 23))
        self.modus_3_stop.setCheckable(False)
        self.modus_3_stop.setObjectName(_fromUtf8("modus_3_stop"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(10, 190, 181, 131))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("MICROSOFT-Xbox-360-Wireless-Controller.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.modus_3_anfrage = QtGui.QPushButton(self.tab_2)
        self.modus_3_anfrage.setEnabled(False)
        self.modus_3_anfrage.setGeometry(QtCore.QRect(20, 82, 161, 41))
        self.modus_3_anfrage.setObjectName(_fromUtf8("modus_3_anfrage"))
        self.modus_wahl.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.test_button = QtGui.QPushButton(self.tab_4)
        self.test_button.setGeometry(QtCore.QRect(10, 130, 101, 31))
        self.test_button.setObjectName(_fromUtf8("test_button"))
        self.andere_apps = QtGui.QListWidget(self.tab_4)
        self.andere_apps.setGeometry(QtCore.QRect(10, 10, 181, 111))
        self.andere_apps.setObjectName(_fromUtf8("andere_apps"))
        self.modus_wahl.addTab(self.tab_4, _fromUtf8(""))
        self.ausgabe = QtGui.QTextEdit(self.centralWidget)
        self.ausgabe.setGeometry(QtCore.QRect(10, 10, 301, 351))
        self.ausgabe.setMouseTracking(True)
        self.ausgabe.setReadOnly(True)
        self.ausgabe.setObjectName(_fromUtf8("ausgabe"))
        mainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 636, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuExterner_Client = QtGui.QMenu(self.menuBar)
        self.menuExterner_Client.setObjectName(_fromUtf8("menuExterner_Client"))
        mainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(mainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(mainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        mainWindow.setStatusBar(self.statusBar)
        self.close = QtGui.QAction(mainWindow)
        self.close.setObjectName(_fromUtf8("close"))
        self.actionHilfe = QtGui.QAction(mainWindow)
        self.actionHilfe.setObjectName(_fromUtf8("actionHilfe"))
        self.actionEinstellung = QtGui.QAction(mainWindow)
        self.actionEinstellung.setObjectName(_fromUtf8("actionEinstellung"))
        self.menuExterner_Client.addAction(self.actionEinstellung)
        self.menuExterner_Client.addAction(self.actionHilfe)
        self.menuExterner_Client.addAction(self.close)
        self.menuBar.addAction(self.menuExterner_Client.menuAction())

        self.retranslateUi(mainWindow)
        self.modus_wahl.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "Externe Robotersteuerung", None))
        self.drop_befehle_senden.setText(_translate("mainWindow", "Senden", None))
        self.manuelle_befehle_senden.setText(_translate("mainWindow", "Senden", None))
        self.Zustandsangabe_1.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Modus deaktiviert.</p></body></html>", None))
        self.modus_1_start.setText(_translate("mainWindow", "Start", None))
        self.modus_1_stop.setText(_translate("mainWindow", "Stopp", None))
        self.empfange_button.setText(_translate("mainWindow", "Nachricht empfangen", None))
        self.modus_wahl.setTabText(self.modus_wahl.indexOf(self.tab), _translate("mainWindow", "Manuell", None))
        self.programm_senden_1.setText(_translate("mainWindow", "Programm Senden", None))
        self.programm_senden_2.setText(_translate("mainWindow", "Wirklich Senden", None))
        self.Zustandsangabe_2.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Modus deaktiviert.</p></body></html>", None))
        self.modus_2_start.setText(_translate("mainWindow", "Start", None))
        self.modus_2_stop.setText(_translate("mainWindow", "Stopp", None))
        self.modus_wahl.setTabText(self.modus_wahl.indexOf(self.tab_3), _translate("mainWindow", "Programm", None))
        self.modus_3_senden.setText(_translate("mainWindow", "Übertragung starten", None))
        self.Zustandsangabe_3.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Modus deaktiviert.</p></body></html>", None))
        self.modus_3_start.setText(_translate("mainWindow", "Start", None))
        self.modus_3_stop.setText(_translate("mainWindow", "Stopp", None))
        self.modus_3_anfrage.setText(_translate("mainWindow", "Zugriffsanfrage", None))
        self.modus_wahl.setTabText(self.modus_wahl.indexOf(self.tab_2), _translate("mainWindow", "Controller", None))
        self.test_button.setText(_translate("mainWindow", "Test", None))
        self.modus_wahl.setTabText(self.modus_wahl.indexOf(self.tab_4), _translate("mainWindow", "Test", None))
        self.menuExterner_Client.setTitle(_translate("mainWindow", "Externer Client", None))
        self.close.setText(_translate("mainWindow", "Schließen", None))
        self.actionHilfe.setText(_translate("mainWindow", "Hilfe", None))
        self.actionEinstellung.setText(_translate("mainWindow", "Einstellung", None))

